-- WHERE 절, MIN()
SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME = (
    SELECT MIN(DATETIME)
    FROM ANIMAL_INS
);

# -- LIMIT
# SELECT NAME
# FROM ANIMAL_INS
# ORDER BY DATETIME ASC
# LIMIT 1;

# -- ORACLE
# SELECT NAME
# FROM (
#     SELECT NAME
#     FROM ANIMAL_INS
#     ORDER BY DATETIME ASC;
# )
# WHERE ROWNUM=1;